CREATE TABLE tb_help_menus (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGSERIAL NOT NULL,
    image VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL UNIQUE,
    subtitle VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES tb_users(id) ON DELETE CASCADE
);